
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nyc_tlc_trips'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["week_4/models"]
analysis-paths: ["week_4/analyses"]
test-paths: ["week_4/tests"]
seed-paths: ["week_4/seeds"]
macro-paths: ["week_4/macros"]
snapshot-paths: ["week_4/snapshots"]

target-path: "week_4/target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "week_4/target"
  - "week_4/dbt_packages"
  - "week_4/dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  nyc_tlc_trips:
    # Applies to all files under models/example/
    staging:
      materialized: view
    core:
      materialized: table

vars:
  payment_type_values: [1, 2, 3, 4, 5, 6]

seeds: 
  nyc_tlc_trips:
    taxi_zone_lookup:
      +column_types:
        locationid: numeric

